libreview:
  auth:
    password: "xxx"
    username: "xxx"
  importConfig:
    apiEndpoint: https://api.libreview.ru
    culture: ru-RU
    deviceSettings:
      firmwareVersion: 2.8.2
      glucoseTargetRangeHighInMgPerDl: 144
      glucoseTargetRangeLowInMgPerDl: 90
      hardwareDescriptor: Redmi Note 8 Pro
      hardwareName: Xiaomi
      modelName: com.freestylelibre.app.ru
      osType: Android
      osVersion: "29"
      selectedCarbType: grams of carbs
      selectedLanguage: ru_RU
      selectedTimeFormat: 24hr
      uniqueIdentifier: ""
    domain: Libreview
    gatewayType: FSLibreLink.Android
    uom: mmol/L
nightscout:
  apiToken: ""
  url: ""

